<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-17T13:48:27 IST" name="Suite" finished-at="2024-09-17T13:49:43 IST" duration-ms="76180">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.LoginErrorValidation()[pri:0, instance:Pallavi_Practise_Project.Test.ErrorValidationTest@4b6690c0]" name="LoginErrorValidation" class="Pallavi_Practise_Project.Test.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:Pallavi_Practise_Project.Test.SubmitOrderTest@40238dd0]" name="submitOrder" class="Pallavi_Practise_Project.Test.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-09-17T13:48:27 IST" name="Submit Order Test" finished-at="2024-09-17T13:49:41 IST" duration-ms="74040">
      <class name="Pallavi_Practise_Project.Test.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Pallavi_Practise_Project.Test.SubmitOrderTest@40238dd0]" started-at="2024-09-17T13:48:27 IST" name="launchApplication" finished-at="2024-09-17T13:48:44 IST" duration-ms="16940" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Pallavi_Practise_Project.Test.SubmitOrderTest@40238dd0]" started-at="2024-09-17T13:48:44 IST" name="submitOrder" data-provider="getData" finished-at="2024-09-17T13:48:50 IST" duration-ms="5602" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Test@123, product=ADIDAS ORIGINAL, email=Pallavi+01@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Pallavi_Practise_Project.Test.SubmitOrderTest@40238dd0]" started-at="2024-09-17T13:48:50 IST" name="tearDown" finished-at="2024-09-17T13:48:50 IST" duration-ms="105" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Pallavi_Practise_Project.Test.SubmitOrderTest@40238dd0]" started-at="2024-09-17T13:48:50 IST" name="launchApplication" finished-at="2024-09-17T13:49:21 IST" duration-ms="31050" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Pallavi_Practise_Project.Test.SubmitOrderTest@40238dd0]" started-at="2024-09-17T13:49:21 IST" name="submitOrder" data-provider="getData" finished-at="2024-09-17T13:49:26 IST" duration-ms="5072" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Test@123, product=ZARA COAT 3, email=Tomar+01@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Pallavi_Practise_Project.Test.SubmitOrderTest@40238dd0]" started-at="2024-09-17T13:49:26 IST" name="tearDown" finished-at="2024-09-17T13:49:26 IST" duration-ms="96" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Pallavi_Practise_Project.Test.SubmitOrderTest@40238dd0]" started-at="2024-09-17T13:49:26 IST" name="launchApplication" finished-at="2024-09-17T13:49:39 IST" duration-ms="12999" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:Pallavi_Practise_Project.Test.SubmitOrderTest@40238dd0]" started-at="2024-09-17T13:49:39 IST" name="OrderHistoryTest" finished-at="2024-09-17T13:49:40 IST" depends-on-methods="Pallavi_Practise_Project.Test.SubmitOrderTest.submitOrder" duration-ms="1406" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Pallavi_Practise_Project.Test.SubmitOrderTest@40238dd0]" started-at="2024-09-17T13:49:41 IST" name="tearDown" finished-at="2024-09-17T13:49:41 IST" duration-ms="262" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Pallavi_Practise_Project.Test.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
    <test started-at="2024-09-17T13:48:27 IST" name="Error Validation Test" finished-at="2024-09-17T13:49:43 IST" duration-ms="76180">
      <class name="Pallavi_Practise_Project.Test.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Pallavi_Practise_Project.Test.ErrorValidationTest@4b6690c0]" started-at="2024-09-17T13:48:27 IST" name="launchApplication" finished-at="2024-09-17T13:49:00 IST" duration-ms="32811" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:Pallavi_Practise_Project.Test.ErrorValidationTest@4b6690c0]" started-at="2024-09-17T13:49:00 IST" name="LoginErrorValidation" finished-at="2024-09-17T13:49:01 IST" duration-ms="1149" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Pallavi_Practise_Project.Test.ErrorValidationTest.LoginErrorValidation(ErrorValidationTest.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Pallavi_Practise_Project.Test.ErrorValidationTest@4b6690c0]" started-at="2024-09-17T13:49:01 IST" name="tearDown" finished-at="2024-09-17T13:49:01 IST" duration-ms="99" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Pallavi_Practise_Project.Test.ErrorValidationTest@4b6690c0]" started-at="2024-09-17T13:49:01 IST" name="launchApplication" finished-at="2024-09-17T13:49:21 IST" duration-ms="20083" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:Pallavi_Practise_Project.Test.ErrorValidationTest@4b6690c0]" started-at="2024-09-17T13:49:21 IST" name="LoginErrorValidation" finished-at="2024-09-17T13:49:22 IST" duration-ms="1176" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Pallavi_Practise_Project.Test.ErrorValidationTest.LoginErrorValidation(ErrorValidationTest.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Pallavi_Practise_Project.Test.ErrorValidationTest@4b6690c0]" started-at="2024-09-17T13:49:23 IST" name="tearDown" finished-at="2024-09-17T13:49:23 IST" duration-ms="180" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Pallavi_Practise_Project.Test.ErrorValidationTest@4b6690c0]" started-at="2024-09-17T13:49:23 IST" name="launchApplication" finished-at="2024-09-17T13:49:39 IST" duration-ms="16324" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:Pallavi_Practise_Project.Test.ErrorValidationTest@4b6690c0]" started-at="2024-09-17T13:49:39 IST" name="ProductErrorValidation" finished-at="2024-09-17T13:49:42 IST" duration-ms="3001" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Pallavi_Practise_Project.Test.ErrorValidationTest@4b6690c0]" started-at="2024-09-17T13:49:42 IST" name="tearDown" finished-at="2024-09-17T13:49:43 IST" duration-ms="773" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Pallavi_Practise_Project.Test.ErrorValidationTest -->
    </test> <!-- Error Validation Test -->
  </suite> <!-- Suite -->
</testng-results>
